//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Application", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter fullname, email and phone number to proceed..
        /// </summary>
        internal static string BuyerDetailMandatory {
            get {
                return ResourceManager.GetString("BuyerDetailMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelPayment {
            get {
                return ResourceManager.GetString("CancelPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! Please try again later..
        /// </summary>
        internal static string CommonErrorMessage {
            get {
                return ResourceManager.GetString("CommonErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a domestic bank to proceed..
        /// </summary>
        internal static string DomesticBankMandatory {
            get {
                return ResourceManager.GetString("DomesticBankMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by domestic ATM cards..
        /// </summary>
        internal static string PaybyATMOnline {
            get {
                return ResourceManager.GetString("PaybyATMOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to proceed payment, Your ATM cards need to be registered Internet-Banking or online payment services. &lt;br/&gt;Please choose your bank:.
        /// </summary>
        internal static string PaybyATMOnlineNote {
            get {
                return ResourceManager.GetString("PaybyATMOnlineNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by international debit/credit cards(Visa, Mastercard, JCB).
        /// </summary>
        internal static string PaybyCreditCard {
            get {
                return ResourceManager.GetString("PaybyCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by Ngân Lượng e-wallet.
        /// </summary>
        internal static string PaybyNLWallet {
            get {
                return ResourceManager.GetString("PaybyNLWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free registration for Ngan Luong e-wallet &lt;a href=&quot;https://www.nganluong.vn/?portal=nganluong&amp;amp;page=user_register&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string PaybyNLWalletDescription {
            get {
                return ResourceManager.GetString("PaybyNLWalletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected and licensed by the State Bank, Nganluong is continuously voted as &quot;The most popular e-wallet and online payment gateway&quot; in 2 consecutive years and was awarded Sao Khue for &quot;Best electronic wallet &quot; by Ministry of Information and Communication..
        /// </summary>
        internal static string PaymentGatewayDescription {
            get {
                return ResourceManager.GetString("PaymentGatewayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a payment method below:.
        /// </summary>
        internal static string PleaseChoosePaymentMethod {
            get {
                return ResourceManager.GetString("PleaseChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After filling in your information below, you will be directed to Ngan Luong Payment Gateway page to complete payment:.
        /// </summary>
        internal static string PleaseEnterFollowingInformation {
            get {
                return ResourceManager.GetString("PleaseEnterFollowingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed payment.
        /// </summary>
        internal static string ProceedPayment {
            get {
                return ResourceManager.GetString("ProceedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated ONLINE PAYMENT GATEWAY.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HebeVietNam Payment Gateway.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
